### ISSUE TITLE
In offline can still connect via IP

### ISSUE THREAD

**Issue by emilebosch** [lynaghk/sandboxtron#3]
Doesn't resolve the DNS but can still telnet when IP given

```
telnet 172.217.19.196 443
```

**Comment by emilebosch** [comment]
Removing the network section does help tho but then local connections are also not allowed

**Comment by emilebosch** [comment]
Got it to work for rails:
```
(allow network-bind (local ip "*:3000"))
(allow network-inbound)
(allow network-outbound (remote ip "localhost:5432"))
```

It can't do any outside calls (but it can connect to psql

```
bash-3.2$ telnet 142.250.179.132 443
Trying 142.250.179.132...
telnet: connect to address 142.250.179.132: Operation not permitted
telnet: Unable to connect to remote host
```

**Comment by lynaghk** [comment]
Thanks for the report @emilebosch!
I did some tests and looked more closely at the unofficial Apple-Sandbox-Guide-v1.0.pdf "docs" and updated the `allow` filter to only allow connections to localhost.
My mistake earlier was in also allowing connections from (the `local` keyword) localhost, which allowed any connection through if you bothered to type out the ip (since DNS was still blocked by the base config).

Give the following base config a shot, it should let you connection to/from localhost but not connect to anything beyond that.
